using Construction.Application.Common.Interfaces;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace Construction.Infrastructure.Storage;

/// <summary>
/// Stores files on the local disk.
/// </summary>
/// <remarks>
/// The default, so a clone runs and the tests exercise the real upload path
/// without MinIO or an AWS account. Not suitable for more than one API
/// instance — two replicas would each hold half the files — which is why
/// configuring a bucket switches to <see cref="S3FileStorage"/>.
/// </remarks>
public class FileSystemFileStorage : IFileStorage
{
    private readonly string _root;
    private readonly ILogger<FileSystemFileStorage> _logger;

    public FileSystemFileStorage(
        IOptions<FileStorageSettings> settings,
        ILogger<FileSystemFileStorage> logger)
    {
        _root = Path.GetFullPath(settings.Value.RootPath);
        _logger = logger;

        Directory.CreateDirectory(_root);

        _logger.LogInformation(
            "File storage is the local disk at {Root}. Configure FileStorage:Bucket " +
            "to use object storage instead.",
            _root);
    }

    public async Task SaveAsync(
        string storageKey,
        Stream content,
        string contentType,
        CancellationToken cancellationToken = default)
    {
        var path = ResolvePath(storageKey);

        Directory.CreateDirectory(Path.GetDirectoryName(path)!);

        await using var file = new FileStream(
            path, FileMode.Create, FileAccess.Write, FileShare.None, 81920, useAsync: true);

        await content.CopyToAsync(file, cancellationToken);
    }

    public Task<Stream?> OpenReadAsync(
        string storageKey,
        CancellationToken cancellationToken = default)
    {
        var path = ResolvePath(storageKey);

        if (!File.Exists(path))
        {
            return Task.FromResult<Stream?>(null);
        }

        Stream stream = new FileStream(
            path, FileMode.Open, FileAccess.Read, FileShare.Read, 81920, useAsync: true);

        return Task.FromResult<Stream?>(stream);
    }

    public Task DeleteAsync(string storageKey, CancellationToken cancellationToken = default)
    {
        var path = ResolvePath(storageKey);

        if (File.Exists(path))
        {
            File.Delete(path);
        }

        return Task.CompletedTask;
    }

    /// <summary>
    /// Turns a storage key into a path, refusing anything that would land
    /// outside the storage root.
    /// </summary>
    /// <remarks>
    /// Keys are generated by the application and never taken from a request,
    /// so this should be unreachable. It is here because "should be" is what
    /// every path-traversal write has in common: the check costs nothing, and
    /// the thing it prevents is writing anywhere on the disk.
    /// </remarks>
    private string ResolvePath(string storageKey)
    {
        var combined = Path.GetFullPath(Path.Combine(_root, storageKey));

        if (!combined.StartsWith(_root + Path.DirectorySeparatorChar, StringComparison.Ordinal)
            && combined != _root)
        {
            throw new InvalidOperationException(
                $"Storage key '{storageKey}' resolves outside the storage root.");
        }

        return combined;
    }
}
