using System.Text.Json;
using Construction.Application.Features.Audit.Models;
using Construction.Application.Features.Audit.Queries.GetAuditTrail;
using Construction.Application.Features.Employees.Commands.AssignEmployeeToProject;
using Construction.Application.Features.Employees.Commands.CreateEmployee;
using Construction.Application.Features.Employees.Commands.DeleteEmployee;
using Construction.Application.Features.Employees.Commands.RemoveEmployeeFromProject;
using Construction.Application.Features.Employees.Commands.UpdateEmployee;
using Construction.Application.Features.Locations.Commands.ReportLocations;
using Construction.Application.Features.Users.Commands.SetUserPassword;
using Construction.Domain.Entities;
using Construction.Domain.Enums;
using Microsoft.EntityFrameworkCore;

namespace Construction.IntegrationTests;

/// <summary>
/// Who changed what, and when.
/// </summary>
/// <remarks>
/// <para>
/// The trail is written by a persistence interceptor, so what needs proving is
/// not that a method works but that there is no way around it: a handler that
/// modifies an audited entity gets a row whether or not anybody remembered.
/// </para>
/// <para>
/// The security half matters as much as the coverage half. An audit trail is a
/// long-lived, administrator-readable copy of every field that changed, which
/// makes it the second place a password hash can come to rest — and unlike the
/// first, it outlives the account.
/// </para>
/// </remarks>
[Collection(DatabaseCollection.Name)]
public class AuditTrailTests : IntegrationTestBase
{
    public AuditTrailTests(DatabaseFixture fixture) : base(fixture)
    {
    }

    private static readonly JsonSerializerOptions Json = new(JsonSerializerDefaults.Web);

    private Task<List<AuditEntry>> TrailFor<T>(Guid id) =>
        InScope(scope => scope.Db.AuditEntries
            .AsNoTracking()
            .Where(a => a.EntityName == typeof(T).Name && a.EntityId == id)
            .OrderBy(a => a.Id)
            .ToListAsync());

    /// <summary>
    /// The most recent entry for a record.
    /// </summary>
    /// <remarks>
    /// Seeding an entity is itself an audited creation, so a test that seeds
    /// and then edits has two rows and wants the second. That the seed is
    /// recorded at all is the interceptor working — there is no way to write
    /// an audited entity without leaving a trail, including from a test
    /// helper.
    /// </remarks>
    private async Task<AuditEntry> LatestFor<T>(Guid id)
    {
        var trail = await TrailFor<T>(id);
        return trail[^1];
    }

    private static Dictionary<string, Change> ChangesOf(AuditEntry entry) =>
        JsonSerializer.Deserialize<Dictionary<string, Change>>(entry.ChangesJson, Json)!;

    private sealed record Change(string? From, string? To);

    private static void ActAs(TestScope scope, User user) =>
        scope.CurrentUser.SignInAs(user.Id, user.Role, null, user.Email);

    private static CreateEmployeeCommand NewEmployee(string number) => new()
    {
        EmployeeNumber = number,
        FirstName = "Ivan",
        LastName = "Horvat",
        Position = "Site Manager",
        EmploymentDate = new DateOnly(2020, 3, 1),
        Status = EmployeeStatus.Active
    };

    // ---- recording -------------------------------------------------------

    [Fact]
    public async Task Creating_a_record_is_written_down_with_what_it_started_as()
    {
        var employee = await InScope(scope =>
            scope.Send(NewEmployee($"EMP-AUD-{Guid.NewGuid().ToString("N")[..6]}")));

        var entry = Assert.Single(await TrailFor<Employee>(employee.Id));

        Assert.Equal(AuditAction.Created, entry.Action);
        Assert.Equal("Employee", entry.EntityName);

        var changes = ChangesOf(entry);

        // The whole starting state, so the trail can describe the record
        // without the record still existing.
        Assert.Equal("Ivan", changes["FirstName"].To);
        Assert.Equal("Horvat", changes["LastName"].To);
        Assert.Equal("Site Manager", changes["Position"].To);
        Assert.All(changes.Values, change => Assert.Null(change.From));
    }

    [Fact]
    public async Task A_created_record_is_filed_under_the_id_it_actually_got()
    {
        // The interceptor reads the key before the insert, which only works
        // because EF generates Guid keys on the client. Were they generated by
        // the database, every creation would be filed under an empty id and
        // the trail would be unusable in exactly the case it is needed most.
        var employee = await InScope(scope =>
            scope.Send(NewEmployee($"EMP-ID-{Guid.NewGuid().ToString("N")[..6]}")));

        var entry = Assert.Single(await TrailFor<Employee>(employee.Id));

        Assert.NotEqual(Guid.Empty, entry.EntityId);
        Assert.Equal(employee.Id, entry.EntityId);
    }

    [Fact]
    public async Task An_edit_records_only_what_moved()
    {
        var employee = await InScope(scope => TestData.SeedEmployeeAsync(scope));

        await InScope(scope => scope.Send(new UpdateEmployeeCommand
        {
            Id = employee.Id,
            EmployeeNumber = employee.EmployeeNumber,
            FirstName = "Petra",
            LastName = employee.LastName,
            Position = employee.Position,
            EmploymentDate = employee.EmploymentDate,
            Status = EmployeeStatus.OnLeave
        }));

        var entry = await LatestFor<Employee>(employee.Id);
        var changes = ChangesOf(entry);

        Assert.Equal(AuditAction.Updated, entry.Action);

        Assert.Equal("Ivan", changes["FirstName"].From);
        Assert.Equal("Petra", changes["FirstName"].To);
        Assert.Equal("Active", changes["Status"].From);
        Assert.Equal("OnLeave", changes["Status"].To);

        // The handler assigns every field from the command, so EF marks them
        // all modified. Recording those would bury the two real changes in
        // "Position: Site Manager → Site Manager".
        Assert.DoesNotContain("LastName", changes.Keys);
        Assert.DoesNotContain("Position", changes.Keys);
    }

    [Fact]
    public async Task An_enum_is_recorded_by_name_and_not_by_number()
    {
        // A number is meaningless to whoever reads the trail, and renumbering
        // the enum later would silently rewrite what the history says
        // happened.
        var employee = await InScope(scope => TestData.SeedEmployeeAsync(scope));

        await InScope(scope => scope.Send(new UpdateEmployeeCommand
        {
            Id = employee.Id,
            EmployeeNumber = employee.EmployeeNumber,
            FirstName = employee.FirstName,
            LastName = employee.LastName,
            Position = employee.Position,
            EmploymentDate = employee.EmploymentDate,
            Status = EmployeeStatus.Terminated
        }));

        var changes = ChangesOf(await LatestFor<Employee>(employee.Id));

        Assert.Equal("Terminated", changes["Status"].To);
    }

    [Fact]
    public async Task A_save_that_changed_nothing_leaves_no_trace()
    {
        // Re-saving a form untouched is the most common write in an admin
        // panel. A row for each would make the trail mostly noise, in the one
        // place noise is most expensive to read through.
        var employee = await InScope(scope => TestData.SeedEmployeeAsync(scope));

        var unchanged = new UpdateEmployeeCommand
        {
            Id = employee.Id,
            EmployeeNumber = employee.EmployeeNumber,
            FirstName = employee.FirstName,
            LastName = employee.LastName,
            Position = employee.Position,
            EmploymentDate = employee.EmploymentDate,
            Status = employee.Status
        };

        var before = (await TrailFor<Employee>(employee.Id)).Count;

        await InScope(scope => scope.Send(unchanged));

        Assert.Equal(before, (await TrailFor<Employee>(employee.Id)).Count);
    }

    [Fact]
    public async Task A_soft_delete_is_recorded_as_a_deletion_and_not_as_an_edit()
    {
        // The soft-delete interceptor has already turned this into a
        // modification by the time the trail sees it. Recorded naively it
        // would read "IsDeleted: false → true", which is true, unhelpful, and
        // impossible to filter on.
        var employee = await InScope(scope => TestData.SeedEmployeeAsync(scope));

        await InScope(scope => scope.Send(new DeleteEmployeeCommand(employee.Id)));

        var entry = await LatestFor<Employee>(employee.Id);

        Assert.Equal(AuditAction.Deleted, entry.Action);
    }

    [Fact]
    public async Task A_soft_delete_does_not_pretend_the_data_was_lost()
    {
        // A soft-deleted row is still on disk under its flag, so there is
        // nothing to preserve a copy of. Recording the whole record as
        // "value → null" would read as destruction, which is the opposite of
        // what happened and the opposite of what a recovery would need.
        //
        // This is also what pins the interceptor ordering. Registered before
        // the soft-delete interceptor, the entity would still be in the
        // Deleted state here and would get the full snapshot below — while
        // still being reported as Deleted, which is why asserting the action
        // alone was not enough.
        var employee = await InScope(scope => TestData.SeedEmployeeAsync(scope));

        await InScope(scope => scope.Send(new DeleteEmployeeCommand(employee.Id)));

        var entry = await LatestFor<Employee>(employee.Id);
        var changes = ChangesOf(entry);

        Assert.Equal(AuditAction.Deleted, entry.Action);
        Assert.DoesNotContain("FirstName", changes.Keys);
        Assert.DoesNotContain("EmployeeNumber", changes.Keys);
    }

    [Fact]
    public async Task A_hard_delete_records_what_was_lost()
    {
        // The other branch, and a real path: removing a posting that has not
        // started yet deletes the row outright rather than end-dating it,
        // because there is nothing to preserve. This is the last moment the
        // values exist, so the trail takes a copy.
        var employee = await InScope(scope => TestData.SeedEmployeeAsync(scope));
        var project = await InScope(scope => TestData.SeedProjectAsync(scope));

        var startsNextWeek = DateOnly.FromDateTime(DateTime.UtcNow).AddDays(7);

        await InScope(scope => scope.Send(
            new AssignEmployeeToProjectCommand(employee.Id, project.Id)
            {
                StartDate = startsNextWeek
            }));

        var postingId = await InScope(scope => scope.Db.EmployeeProjects
            .Where(ep => ep.EmployeeId == employee.Id && ep.ProjectId == project.Id)
            .Select(ep => ep.Id)
            .SingleAsync());

        await InScope(scope => scope.Send(
            new RemoveEmployeeFromProjectCommand(employee.Id, project.Id)));

        var entry = await LatestFor<EmployeeProject>(postingId);
        var changes = ChangesOf(entry);

        Assert.Equal(AuditAction.Deleted, entry.Action);

        // Everything the row held, on its way out.
        Assert.Equal(employee.Id.ToString(), changes["EmployeeId"].From);
        Assert.Equal(project.Id.ToString(), changes["ProjectId"].From);
        Assert.All(changes.Values, change => Assert.Null(change.To));
    }

    [Fact]
    public async Task The_trail_outlives_the_record_it_describes()
    {
        // The point of the whole thing. A deleted employee's history has to
        // survive the deletion, or the trail says least about the changes most
        // worth asking about.
        var employee = await InScope(scope =>
            scope.Send(NewEmployee($"EMP-GONE-{Guid.NewGuid().ToString("N")[..6]}")));

        await InScope(scope => scope.Send(new DeleteEmployeeCommand(employee.Id)));

        var trail = await TrailFor<Employee>(employee.Id);

        Assert.Equal(2, trail.Count);
        Assert.Equal(AuditAction.Created, trail[0].Action);
        Assert.Equal(AuditAction.Deleted, trail[1].Action);
    }

    // ---- who -------------------------------------------------------------

    [Fact]
    public async Task The_trail_records_who_made_the_change_as_they_were_at_the_time()
    {
        var actor = await InScope(scope =>
            TestData.SeedUserAsync(scope, UserRole.Admin, email: "auditor@construction.test"));

        var employee = await InScope(scope =>
        {
            ActAs(scope, actor);
            scope.CurrentUser.IpAddress = "203.0.113.7";
            return TestData.SeedEmployeeAsync(scope);
        });

        var entry = Assert.Single(await TrailFor<Employee>(employee.Id));

        Assert.Equal(actor.Id, entry.UserId);
        Assert.Equal("auditor@construction.test", entry.UserEmail);
        Assert.Equal(UserRole.Admin, entry.UserRole);
        Assert.Equal("203.0.113.7", entry.IpAddress);
    }

    [Fact]
    public async Task The_actor_s_details_are_copied_in_rather_than_looked_up_later()
    {
        // The account can be renamed, promoted or deleted afterwards. The
        // trail has to say who did it at the time — a join would either
        // rewrite history or leave a dangling id.
        var actor = await InScope(scope =>
            TestData.SeedUserAsync(scope, UserRole.Admin, email: "before@construction.test"));

        var employee = await InScope(scope =>
        {
            ActAs(scope, actor);
            return TestData.SeedEmployeeAsync(scope);
        });

        await InScope(async scope =>
        {
            var tracked = await scope.Db.Users.SingleAsync(u => u.Id == actor.Id);
            tracked.Email = "after@construction.test";
            tracked.Role = UserRole.Worker;
            await scope.Db.SaveChangesAsync();
        });

        var entry = Assert.Single(await TrailFor<Employee>(employee.Id));

        Assert.Equal("before@construction.test", entry.UserEmail);
        Assert.Equal(UserRole.Admin, entry.UserRole);
    }

    [Fact]
    public async Task A_change_with_nobody_signed_in_is_still_recorded()
    {
        // Background jobs and migrations write too. Dropping those rows
        // because there is no user would leave gaps exactly where an
        // unexplained change is most alarming.
        var employee = await InScope(scope =>
        {
            scope.CurrentUser.SignOut();
            return TestData.SeedEmployeeAsync(scope);
        });

        var entry = Assert.Single(await TrailFor<Employee>(employee.Id));

        Assert.Null(entry.UserId);
        Assert.Null(entry.UserEmail);
        Assert.Equal(AuditAction.Created, entry.Action);
    }

    // ---- what is deliberately not recorded --------------------------------

    [Fact]
    public async Task A_password_change_does_not_put_the_hash_in_the_trail()
    {
        // The reason NotAuditedAttribute exists. Without it a password change
        // writes both the old and the new hash into a table that is read by
        // administrators and outlives the account — turning the audit trail
        // into an offline-cracking target with a change history attached.
        var admin = await InScope(scope => TestData.SeedUserAsync(scope, UserRole.SuperAdmin));
        var subject = await InScope(scope => TestData.SeedUserAsync(scope, UserRole.Worker));

        var hashBefore = await InScope(scope => scope.Db.Users
            .Where(u => u.Id == subject.Id)
            .Select(u => u.PasswordHash)
            .SingleAsync());

        await InScope(scope =>
        {
            ActAs(scope, admin);
            return scope.Send(new SetUserPasswordCommand
            {
                Id = subject.Id,
                NewPassword = "Replaced1234!"
            });
        });

        var hashAfter = await InScope(scope => scope.Db.Users
            .Where(u => u.Id == subject.Id)
            .Select(u => u.PasswordHash)
            .SingleAsync());

        Assert.NotEqual(hashBefore, hashAfter);

        var trail = await TrailFor<User>(subject.Id);

        foreach (var entry in trail)
        {
            Assert.DoesNotContain("PasswordHash", ChangesOf(entry).Keys);

            // Not just the key — the value must not have landed under some
            // other name either.
            Assert.DoesNotContain(hashBefore, entry.ChangesJson);
            Assert.DoesNotContain(hashAfter, entry.ChangesJson);
        }
    }

    [Fact]
    public async Task Nothing_that_looks_like_a_credential_is_ever_recorded()
    {
        // The safety net, asserted across every row the whole suite has
        // written rather than on one entity — the risk is a field added later
        // by somebody who did not read the attribute.
        var suspicious = new[] { "password", "hash", "token", "secret" };

        var keys = await InScope(async scope =>
        {
            var rows = await scope.Db.AuditEntries
                .AsNoTracking()
                .Select(a => a.ChangesJson)
                .Take(2000)
                .ToListAsync();

            return rows
                .SelectMany(json =>
                    JsonSerializer.Deserialize<Dictionary<string, Change>>(json, Json)!.Keys)
                .Distinct()
                .ToList();
        });

        Assert.NotEmpty(keys);

        Assert.All(keys, key => Assert.DoesNotContain(
            suspicious,
            fragment => key.Contains(fragment, StringComparison.OrdinalIgnoreCase)));
    }

    [Fact]
    public async Task High_volume_machine_chatter_is_not_audited()
    {
        // Auditing GPS would add a row per ping — about a million a month for
        // a hundred-person crew — to record something no investigation will
        // ever ask about.
        var (employee, user) = await InScope(async scope =>
        {
            var employee = await TestData.SeedEmployeeAsync(scope);
            var user = await TestData.SeedUserAsync(scope, UserRole.Worker, employee.Id);
            return (employee, user);
        });

        var before = await InScope(scope => scope.Db.AuditEntries.CountAsync());

        await InScope(scope =>
        {
            scope.CurrentUser.SignInAs(user.Id, user.Role, employee.Id, user.Email);
            return scope.Send(new ReportLocationsCommand
            {
                Pings =
                [
                    new LocationPing
                    {
                        Latitude = 45.81,
                        Longitude = 15.98,
                        Timestamp = new DateTime(2026, 8, 5, 12, 0, 0, DateTimeKind.Utc)
                    }
                ]
            });
        });

        var after = await InScope(scope => scope.Db.AuditEntries.CountAsync());

        Assert.Equal(before, after);
    }

    // ---- reading it back --------------------------------------------------

    [Fact]
    public async Task The_trail_for_one_record_comes_back_newest_first()
    {
        var employee = await InScope(scope =>
            scope.Send(NewEmployee($"EMP-ORD-{Guid.NewGuid().ToString("N")[..6]}")));

        await InScope(scope => scope.Send(new UpdateEmployeeCommand
        {
            Id = employee.Id,
            EmployeeNumber = employee.EmployeeNumber,
            FirstName = "Petra",
            LastName = employee.LastName,
            Position = employee.Position,
            EmploymentDate = employee.EmploymentDate,
            Status = EmployeeStatus.Active
        }));

        await InScope(scope => scope.Send(new DeleteEmployeeCommand(employee.Id)));

        var page = await InScope(scope => scope.Send(new GetAuditTrailQuery
        {
            EntityName = "Employee",
            EntityId = employee.Id
        }));

        Assert.Equal(
            ["Deleted", "Updated", "Created"],
            page.Items.Select(i => i.Action));
    }

    [Fact]
    public async Task The_changes_come_back_as_an_object_and_not_as_a_string_of_json()
    {
        var employee = await InScope(scope => TestData.SeedEmployeeAsync(scope));

        await InScope(scope => scope.Send(new UpdateEmployeeCommand
        {
            Id = employee.Id,
            EmployeeNumber = employee.EmployeeNumber,
            FirstName = "Renamed",
            LastName = employee.LastName,
            Position = employee.Position,
            EmploymentDate = employee.EmploymentDate,
            Status = employee.Status
        }));

        var page = await InScope(scope => scope.Send(new GetAuditTrailQuery
        {
            EntityName = "Employee",
            EntityId = employee.Id
        }));

        var entry = page.Items.First();
        var change = Assert.Contains("FirstName", entry.Changes);

        Assert.Equal("Ivan", change.From);
        Assert.Equal("Renamed", change.To);
    }

    [Fact]
    public async Task The_type_filter_is_exact_rather_than_a_search()
    {
        // "Employee" must not pull in "EmployeeRate". They are different
        // records with different histories, and a loose match would silently
        // merge them.
        var employee = await InScope(scope => TestData.SeedEmployeeAsync(scope));

        var page = await InScope(scope => scope.Send(new GetAuditTrailQuery
        {
            EntityName = "Employee",
            EntityId = employee.Id
        }));

        Assert.All(page.Items, item => Assert.Equal("Employee", item.EntityName));
    }

    [Fact]
    public async Task The_trail_can_be_read_as_what_one_person_did()
    {
        // The other question an investigation asks, and the reason for the
        // second index.
        var actor = await InScope(scope => TestData.SeedUserAsync(scope, UserRole.Admin));

        var first = await InScope(scope =>
        {
            ActAs(scope, actor);
            return TestData.SeedEmployeeAsync(scope);
        });

        var second = await InScope(scope =>
        {
            ActAs(scope, actor);
            return TestData.SeedEmployeeAsync(scope);
        });

        var page = await InScope(scope => scope.Send(new GetAuditTrailQuery
        {
            UserId = actor.Id,
            PageSize = 100
        }));

        Assert.All(page.Items, item => Assert.Equal(actor.Id, item.UserId));

        var touched = page.Items.Select(i => i.EntityId).ToList();
        Assert.Contains(first.Id, touched);
        Assert.Contains(second.Id, touched);
    }

    [Fact]
    public async Task The_trail_can_be_narrowed_to_one_kind_of_action()
    {
        var actor = await InScope(scope => TestData.SeedUserAsync(scope, UserRole.Admin));

        var employee = await InScope(scope =>
        {
            ActAs(scope, actor);
            return TestData.SeedEmployeeAsync(scope);
        });

        await InScope(scope =>
        {
            ActAs(scope, actor);
            return scope.Send(new DeleteEmployeeCommand(employee.Id));
        });

        var page = await InScope(scope => scope.Send(new GetAuditTrailQuery
        {
            UserId = actor.Id,
            Action = AuditAction.Deleted,
            PageSize = 100
        }));

        Assert.All(page.Items, item => Assert.Equal("Deleted", item.Action));
        Assert.Contains(page.Items, item => item.EntityId == employee.Id);
    }

    [Fact]
    public async Task An_id_without_a_type_is_refused()
    {
        // Not pedantry: the index is keyed on the pair, so an id-only query
        // cannot use it and would scan the largest table in the system.
        await Assert.ThrowsAsync<Application.Common.Exceptions.ValidationException>(() =>
            InScope(scope => scope.Send(new GetAuditTrailQuery { EntityId = Guid.NewGuid() })));
    }

    [Fact]
    public async Task Paging_the_trail_neither_repeats_nor_skips_an_entry()
    {
        // Several rows share a timestamp — one save stamps them all from the
        // same clock reading — so ordering by time alone leaves their relative
        // order undefined between the two queries that fetch page one and page
        // two.
        var actor = await InScope(scope => TestData.SeedUserAsync(scope, UserRole.Admin));

        for (var i = 0; i < 12; i++)
        {
            await InScope(scope =>
            {
                ActAs(scope, actor);
                return TestData.SeedEmployeeAsync(scope);
            });
        }

        var seen = new List<long>();

        for (var page = 1; page <= 3; page++)
        {
            var result = await InScope(scope => scope.Send(new GetAuditTrailQuery
            {
                UserId = actor.Id,
                PageNumber = page,
                PageSize = 5
            }));

            seen.AddRange(result.Items.Select(i => i.Id));
        }

        Assert.Equal(12, seen.Count);
        Assert.Equal(12, seen.Distinct().Count());
    }
}
