<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Construction.IntegrationTests</RootNamespace>
    <AssemblyName>Construction.IntegrationTests</AssemblyName>
    <IsPackable>false</IsPackable>
    <!-- See the note in Construction.UnitTests.csproj. -->
    <RollForward>Major</RollForward>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.7" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Construction.Application\Construction.Application.csproj" />
    <ProjectReference Include="..\..\src\Construction.Infrastructure\Construction.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
