import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../../core/network/api_exception.dart';
import '../../../core/utils/formatting.dart';
import '../data/models/bulletin_post.dart';
import 'bulletin_controller.dart';

/// Board text, hand-mapped by language rather than routed through the
/// generated `AppLocalizations`.
///
/// Every other screen in this app pulls its strings from `context.l10n`,
/// which is generated by `flutter gen-l10n` from `lib/l10n/*.arb`. This
/// screen was written in an environment with no Flutter toolchain available
/// to run that generator, so its strings live here instead — a deliberate,
/// temporary exception. Moving them into the `.arb` files and switching this
/// screen to `context.l10n` is the right cleanup once someone with the
/// toolchain touches this feature; nothing here depends on staying separate.
class _BulletinText {
  const _BulletinText({
    required this.title,
    required this.empty,
    required this.postedBy,
  });

  final String title;
  final String empty;
  final String Function(String name) postedBy;

  static const _sr = _BulletinText(
    title: 'Oglasna ploča',
    empty: 'Trenutno nema oglasa.',
    postedBy: _postedBySr,
  );

  static const _en = _BulletinText(
    title: 'Bulletin board',
    empty: 'Nothing posted right now.',
    postedBy: _postedByEn,
  );

  static String _postedBySr(String name) => 'Objavio/la $name';
  static String _postedByEn(String name) => 'Posted by $name';

  static _BulletinText of(BuildContext context) =>
      Localizations.localeOf(context).languageCode == 'sr' ? _sr : _en;
}

class BulletinScreen extends ConsumerWidget {
  const BulletinScreen({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final text = _BulletinText.of(context);
    final state = ref.watch(bulletinControllerProvider);
    final controller = ref.read(bulletinControllerProvider.notifier);

    return Scaffold(
      appBar: AppBar(title: Text(text.title)),
      body: SafeArea(
        child: RefreshIndicator(
          onRefresh: controller.refresh,
          child: state.when(
            loading: () => const Center(child: CircularProgressIndicator()),
            error: (error, _) => ListView(
              children: [
                Padding(
                  padding: const EdgeInsets.all(24),
                  child: Center(
                    child: Text(
                      // English regardless of locale, same as every other
                      // ApiException message not sent by the server — see
                      // ApiException.message.
                      error is ApiException ? error.message : error.toString(),
                    ),
                  ),
                ),
              ],
            ),
            data: (posts) => posts.isEmpty
                ? ListView(
                    children: [
                      Padding(
                        padding: const EdgeInsets.all(32),
                        child: Center(
                          child: Column(
                            children: [
                              Icon(
                                Icons.campaign_outlined,
                                size: 40,
                                color: Theme.of(context).colorScheme.outline,
                              ),
                              const SizedBox(height: 12),
                              Text(
                                text.empty,
                                style: Theme.of(context).textTheme.bodyMedium,
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  )
                : ListView.builder(
                    padding: const EdgeInsets.all(16),
                    itemCount: posts.length,
                    itemBuilder: (context, index) =>
                        _BulletinCard(post: posts[index], text: text),
                  ),
          ),
        ),
      ),
    );
  }
}

class _BulletinCard extends StatelessWidget {
  const _BulletinCard({required this.post, required this.text});

  final BulletinPost post;
  final _BulletinText text;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    return Card(
      margin: const EdgeInsets.only(bottom: 12),
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Container(
              width: 40,
              height: 4,
              decoration: BoxDecoration(
                color: theme.colorScheme.primary,
                borderRadius: BorderRadius.circular(2),
              ),
            ),
            const SizedBox(height: 12),
            Text(
              post.title,
              style: theme.textTheme.titleMedium?.copyWith(
                fontWeight: FontWeight.w700,
              ),
            ),
            const SizedBox(height: 8),
            Text(post.body, style: theme.textTheme.bodyMedium),
            const SizedBox(height: 12),
            Row(
              children: [
                CircleAvatar(
                  radius: 14,
                  child: Text(
                    initialsOf(null, null, fallback: post.createdByName),
                    style: const TextStyle(fontSize: 12),
                  ),
                ),
                const SizedBox(width: 8),
                Expanded(
                  child: Text(
                    '${text.postedBy(post.createdByName)} · '
                    '${formatDateTime(post.createdAt)}',
                    style: theme.textTheme.bodySmall?.copyWith(
                      color: theme.colorScheme.onSurfaceVariant,
                    ),
                    overflow: TextOverflow.ellipsis,
                  ),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}
