#!/usr/bin/env bash
#
# S3 over curl, signed with AWS Signature Version 4.
#
# Sourced by offsite.sh, never executed. Exists so the backup container needs
# nothing but curl and openssl: aws-cli is a Python runtime and rclone is a
# 50 MB binary, and neither is in a postgres:16-alpine. If you would rather
# use one of them, set OFFSITE_COMMAND and none of this runs.
#
# Works against anything that speaks S3 — AWS, MinIO, Backblaze B2, Wasabi,
# Cloudflare R2 — because SigV4 is the same everywhere. The one thing that
# differs is the URL shape, hence OFFSITE_PATH_STYLE.
#
# The algorithm is AWS's, documented at
# https://docs.aws.amazon.com/general/latest/gr/sigv4_signing.html, and it is
# unforgiving: one wrong newline in the canonical request and the provider
# answers 403 with no clue which part was wrong. `scripts/test-offsite.sh`
# runs the whole path against a server that verifies the signature with an
# independent implementation, and refuses a request signed with the wrong
# secret — so a signer emitting gibberish cannot pass.
#
# It has never been run against AWS itself. That needs an account, and it is
# the one part of this that is genuinely somebody else's to do.

: "${OFFSITE_REGION:=us-east-1}"

# MinIO and most self-hosted gateways only do path-style
# (host/bucket/key); AWS wants virtual-host style (bucket.host/key) for
# buckets made after 2020.
: "${OFFSITE_PATH_STYLE:=0}"

# Long enough to move a large dump on a slow link, short enough that a stuck
# upload fails the backup rather than hanging the container until morning.
: "${OFFSITE_TIMEOUT:=1800}"

_hex_sha256() {
    openssl dgst -sha256 -binary | od -An -tx1 | tr -d ' \n'
}

_hex_sha256_file() {
    openssl dgst -sha256 -binary "$1" | od -An -tx1 | tr -d ' \n'
}

# HMAC-SHA256 with a hex key, printing a hex digest. The signing key is
# derived through four of these, each one keyed by the previous digest, so
# everything after the first stays in hex rather than round-tripping through
# a shell variable that would mangle the NUL bytes.
_hmac_hex() {
    local key_hex="$1"
    openssl dgst -sha256 -mac HMAC -macopt "hexkey:${key_hex}" -binary \
        | od -An -tx1 | tr -d ' \n'
}

# The first link in the chain, keyed by the literal secret rather than by hex.
_hmac_from_secret() {
    local secret="$1"
    openssl dgst -sha256 -mac HMAC -macopt "key:${secret}" -binary \
        | od -An -tx1 | tr -d ' \n'
}

# Percent-encodes a URI path, leaving the separators alone.
#
# Keys here are generated by backup.sh — timestamps and a database name — so
# this should never have anything to do. It is here because a signature is
# computed over the encoded path and sent with the encoded path, and if the
# two ever disagree the failure is a 403 that looks like bad credentials.
_uri_encode_path() {
    local path="$1" out="" char
    local i

    for (( i = 0; i < ${#path}; i++ )); do
        char="${path:i:1}"

        case "$char" in
            [A-Za-z0-9._~/-]) out+="$char" ;;
            *) out+="$(printf '%%%02X' "'$char")" ;;
        esac
    done

    printf '%s' "$out"
}

# Builds the Authorization header for one request and echoes it.
#
# Kept separate from the curl calls so the test script can check it against
# AWS's published vector without making a request.
s3_authorization() {
    local method="$1" host="$2" canonical_uri="$3" payload_hash="$4"
    local amz_date="$5" date_stamp="$6"

    local scope="${date_stamp}/${OFFSITE_REGION}/s3/aws4_request"

    # No query string on any request this script makes, hence the empty line.
    # The signed headers are the minimum S3 requires: without `host` the
    # signature would not bind the request to a bucket, and without
    # `x-amz-content-sha256` it would not bind it to the bytes.
    local canonical_request
    canonical_request="$(printf '%s\n%s\n%s\nhost:%s\nx-amz-content-sha256:%s\nx-amz-date:%s\n\n%s\n%s' \
        "$method" \
        "$canonical_uri" \
        "" \
        "$host" \
        "$payload_hash" \
        "$amz_date" \
        "host;x-amz-content-sha256;x-amz-date" \
        "$payload_hash")"

    local canonical_hash
    canonical_hash="$(printf '%s' "$canonical_request" | _hex_sha256)"

    local string_to_sign
    string_to_sign="$(printf 'AWS4-HMAC-SHA256\n%s\n%s\n%s' \
        "$amz_date" "$scope" "$canonical_hash")"

    local k_date k_region k_service k_signing signature
    k_date="$(printf '%s' "$date_stamp" | _hmac_from_secret "AWS4${AWS_SECRET_ACCESS_KEY}")"
    k_region="$(printf '%s' "$OFFSITE_REGION" | _hmac_hex "$k_date")"
    k_service="$(printf '%s' "s3" | _hmac_hex "$k_region")"
    k_signing="$(printf '%s' "aws4_request" | _hmac_hex "$k_service")"
    signature="$(printf '%s' "$string_to_sign" | _hmac_hex "$k_signing")"

    printf 'AWS4-HMAC-SHA256 Credential=%s/%s, SignedHeaders=%s, Signature=%s' \
        "$AWS_ACCESS_KEY_ID" \
        "$scope" \
        "host;x-amz-content-sha256;x-amz-date" \
        "$signature"
}

# Splits OFFSITE_ENDPOINT into the host to sign and the URL to call, which
# differ between the two addressing styles.
_s3_target() {
    local bucket="$1" key="$2"

    local scheme="${OFFSITE_ENDPOINT%%://*}"
    local endpoint_host="${OFFSITE_ENDPOINT#*://}"
    endpoint_host="${endpoint_host%%/*}"

    local host uri

    if [[ "$OFFSITE_PATH_STYLE" == "1" ]]; then
        host="$endpoint_host"
        uri="/${bucket}/${key}"
    else
        host="${bucket}.${endpoint_host}"
        uri="/${key}"
    fi

    # Trailing newline deliberately: `read` returns non-zero at EOF without
    # one, and under `set -e` that aborts the caller before it has made a
    # single request — with no error, because nothing failed.
    printf '%s\t%s\t%s\n' "$host" "$(_uri_encode_path "$uri")" "$scheme"
}

_require_credentials() {
    [[ -n "${AWS_ACCESS_KEY_ID:-}" && -n "${AWS_SECRET_ACCESS_KEY:-}" ]] \
        || die "AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY must be set for off-site copies."
}

s3_put() {
    local bucket="$1" key="$2" file="$3"

    require_tool curl
    require_tool openssl
    _require_credentials

    local host uri scheme
    IFS=$'\t' read -r host uri scheme < <(_s3_target "$bucket" "$key")

    local amz_date date_stamp payload_hash
    amz_date="$(date -u +%Y%m%dT%H%M%SZ)"
    date_stamp="${amz_date%T*}"
    payload_hash="$(_hex_sha256_file "$file")"

    local authorization
    authorization="$(s3_authorization "PUT" "$host" "$uri" "$payload_hash" "$amz_date" "$date_stamp")"

    local status
    status="$(curl --silent --show-error \
        --max-time "$OFFSITE_TIMEOUT" \
        --output /dev/null \
        --write-out '%{http_code}' \
        --request PUT \
        --header "Host: ${host}" \
        --header "x-amz-date: ${amz_date}" \
        --header "x-amz-content-sha256: ${payload_hash}" \
        --header "Authorization: ${authorization}" \
        --upload-file "$file" \
        "${scheme}://${host}${uri}")"

    [[ "$status" == "200" ]] \
        || die "Upload of ${key} failed: HTTP ${status}."
}

s3_get() {
    local bucket="$1" key="$2" dest="$3"

    require_tool curl
    require_tool openssl
    _require_credentials

    local host uri scheme
    IFS=$'\t' read -r host uri scheme < <(_s3_target "$bucket" "$key")

    local amz_date date_stamp
    amz_date="$(date -u +%Y%m%dT%H%M%SZ)"
    date_stamp="${amz_date%T*}"

    # The hash of an empty body, which is what a GET has. AWS's own constant.
    local payload_hash="e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"

    local authorization
    authorization="$(s3_authorization "GET" "$host" "$uri" "$payload_hash" "$amz_date" "$date_stamp")"

    local status
    status="$(curl --silent --show-error \
        --max-time "$OFFSITE_TIMEOUT" \
        --output "$dest" \
        --write-out '%{http_code}' \
        --header "Host: ${host}" \
        --header "x-amz-date: ${amz_date}" \
        --header "x-amz-content-sha256: ${payload_hash}" \
        --header "Authorization: ${authorization}" \
        "${scheme}://${host}${uri}")"

    [[ "$status" == "200" ]] \
        || die "Download of ${key} failed: HTTP ${status}."
}

# The provider's checksum for an object, from a HEAD, with the quotes S3 wraps
# it in stripped.
s3_etag() {
    local bucket="$1" key="$2"

    require_tool curl
    require_tool openssl
    _require_credentials

    local host uri scheme
    IFS=$'\t' read -r host uri scheme < <(_s3_target "$bucket" "$key")

    local amz_date date_stamp
    amz_date="$(date -u +%Y%m%dT%H%M%SZ)"
    date_stamp="${amz_date%T*}"

    local payload_hash="e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"

    local authorization
    authorization="$(s3_authorization "HEAD" "$host" "$uri" "$payload_hash" "$amz_date" "$date_stamp")"

    local headers
    headers="$(curl --silent --show-error \
        --max-time "$OFFSITE_TIMEOUT" \
        --head \
        --header "Host: ${host}" \
        --header "x-amz-date: ${amz_date}" \
        --header "x-amz-content-sha256: ${payload_hash}" \
        --header "Authorization: ${authorization}" \
        "${scheme}://${host}${uri}")"

    printf '%s' "$headers" \
        | grep -i '^etag:' \
        | tr -d '\r"' \
        | sed 's/^[Ee][Tt][Aa][Gg]: *//'
}
