import { chromium } from '@playwright/test';
const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium-1194/chrome-linux/chrome'});
const c=await b.newContext(); await c.addInitScript(()=>localStorage.setItem('construction.locale','en'));
const p=await c.newPage();
await p.goto('http://localhost:5173/login');
await p.waitForTimeout(1200);
console.log('--- labels on login ---');
console.log(await p.evaluate(()=>[...document.querySelectorAll('label')].map(l=>JSON.stringify(l.textContent))));
console.log('--- buttons ---');
console.log(await p.evaluate(()=>[...document.querySelectorAll('button')].map(x=>JSON.stringify((x.getAttribute('aria-label')||x.textContent||'').trim()))));
await p.locator('input[type="email"]').fill('e2e@construction.local');
await p.locator('input[type="password"]').fill('E2ePassword123!');
await p.locator('form button[type="submit"]').click();
await p.waitForTimeout(3000);
console.log('--- url after sign in ---', p.url());
console.log('--- nav links ---');
console.log(await p.evaluate(()=>[...document.querySelectorAll('a')].map(a=>JSON.stringify(a.textContent.trim())).slice(0,8)));
console.log('--- top bar buttons ---');
console.log(await p.evaluate(()=>[...document.querySelectorAll('header button, .MuiAppBar-root button')].map(x=>JSON.stringify((x.getAttribute('aria-label')||x.textContent||'').trim()))));
await b.close();
